---
title: "Computing troubleshooting"
---

If you're having difficulty launching an RStudio session from your reserved container, go to [status.oit.duke.edu](https://status.oit.duke.edu/) and scroll down to **Teaching and Learning Tools**.
Under this heading you'll find an entry called *Container Manager (CMGR Coursework Containers)*.

-   If the status shows something other than `Operational`, this means there is a known incident with the containers.
    Check back later to see if it's been resolved.
    If there's a deadline coming up soon, post on the course Slack to let us know that there's an issue.
    We can look into how quickly it might get resolved and decide on what to do about the deadline accordingly.
    Note: We don't anticipate this to happen regularly, the systems are Operational a huge majority of the time!

-   If the status shows `Operational`, this means the system is expected to be working.
    Check your internet connection, if need be, restart your computer to ensure a fresh new connection.
    If your issue persists, post on the course forum with details on what you've tried and the errors you see (including verbatim errors and/or screenshots).

Another approach is to request a restart of your container.
To do so, select your container as you usually do and then, instead of Login, click on Request Restart.
Read the warning in the next page, and then click once more to restart your container.
